name: healthy_life_tracker
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  
  flutter:
    sdk: flutter

  image: ^4.1.3
  # UI / Utils
  cosmos: 0.5.2
  cupertino_icons: ^1.0.8
  crypto: ^3.0.3
  image_picker:  ^1.1.2
  video_player: ^2.8.6


  flutter_local_notifications: ^17.0.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0
  http: ^1.2.2

  # ðŸ”¥ FIREBASE (ASIL OLAY)
  firebase_core: 3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.10
  
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/nutrition/image/Beverages.png
    - assets/nutrition/image/Diary and Eggs.jpg
    - assets/nutrition/image/fats and oils.png
    - assets/nutrition/image/Fish and Seafood.jpg
    - assets/nutrition/image/fruits.png
    - assets/nutrition/image/grains and cerals.jpg
    - assets/nutrition/image/legumes.jpg
    - assets/nutrition/image/meats and poultry.png
    - assets/nutrition/image/nuts and seeds.png
    - assets/nutrition/image/snack and sweets.png
    - assets/nutrition/image/vegetables.png
    - assets/workout/image/chest exercise.png
    - assets/workout/image/back exercise.png
    - assets/workout/image/leg exercise.png
    - assets/workout/image/shoulder exercise.png
    - assets/workout/image/arm exercise.png
    - assets/workout/image/core abs exercise.png
    - assets/workout/image/cardio exercise.png
    - assets/workout/image/full body exercise.png
    - assets/workout/video/male-barbell-bench-press-side_KciuhbB.mp4
    - assets/workout/video/male-bodyweight-chinup-front.mp4
    - assets/workout/video/male-Bodyweight-diamond-push-ups-side.mp4
    - assets/workout/video/male-bodyweight-pullup-front.mp4
    - assets/workout/video/male-bodyweight-split-squat-front.mp4
    - assets/workout/video/male-Dumbbells-dumbbell-hang-clean-and-press-side.mp4
    - assets/workout/video/male-Recovery-lunge-walking-front.mp4
    - assets/workout/video/male-Recovery-squat-concentric-single-leg-front.mp4
